### ISSUE TITLE
Error handling problems

### ISSUE THREAD

**Issue by antarktidi4** [datfeelbruh/moviesDiary#23]
При запросе без токена не возвращает стандартный объект ошибки(да и в общем ничего не возвращает). При запросе к `/api/movie/{id} ` не возвращает корректное сообщение, возвращает `message: 'No value present'`

**Comment by datfeelbruh** [comment]
при запросе без токена возвращается правильная структура, можешь скинуть пример воспроизведения ошибки?

**Comment by datfeelbruh** [comment]
на ```/api/movie/{id}``` поправлю

**Comment by datfeelbruh** [comment]
поправил эндпоинт
