### ISSUE TITLE
/api/movie/popular property name mistake

### ISSUE THREAD

**Issue by antarktidi4** [datfeelbruh/moviesDiary#24]
`/api/movie/popular` возвращает объект вида
```
{
    "reviewCount": 0,
    "id": 0,
    "title": "string",
    "poster": "string"
 }
  ```
  во всех остальных объектах ссылка на постер указывается в виде `posterUrl`, здесь же: `poster`. Хотелось бы соблюдения конвенции и переименование `poster` в `posterUrl`

**Comment by datfeelbruh** [comment]
будет сделано

**Comment by datfeelbruh** [comment]
сделано
